=encoding UTF-8

=head1 NAME

PhoneNumber::Util - Perlish wrapper of libphonenumber

=for html
<a href=https://travis-ci.org/cv-library/phonenumber-util>
    <img src=https://api.travis-ci.org/cv-library/phonenumber-util.svg>
</a>

=head1 SYNOPSIS

 use PhoneNumber::Util 'is_phone_number';

=head1 SEE ALSO

L<Number::Phone>

=head1 COPYRIGHT AND LICENSE

Copyright © 2018 CV-Library Ltd.

This is free software; you can redistribute it and/or modify it under the
same terms as Perl itself.
